version: '3.6'

networks:
  metoapp-network:
    driver: bridge

services:
  metoapp-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=metoapp-mongo
      - REDIS_URL=metoapp-redis
    depends_on:
      - metoapp-mongo
      - metoapp-redis
    networks:
      - metoapp-network
    links:
      - metoapp-mongo
      - metoapp-redis 
    container_name: metoapp-api
    command: yarn dev
    ports:
      - 3333:3333

  metoapp-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=metoapp-mongo
      - REDIS_URL=metoapp-redis
    depends_on:
      - metoapp-mongo
      - metoapp-redis
    networks:
      - metoapp-network
    links:
      - metoapp-mongo
      - metoapp-redis 
    container_name: metoapp-queue
    command: yarn queue

  metoapp-postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /var/lib/postgresql/data 
    networks:
      - metoapp-network
    
  metoapp-mongo:
    image: bitnami/mongodb:latest
    container_name: metoapp-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - metoapp-network

  metoapp-redis:
    container_name: metoapp-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - metoapp-network